wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.33.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697343594.362554
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      3:
      - 23
      4: 3.10.12
      5: 0.15.9
      6: 4.33.1
      8:
      - 5
